### ISSUE TITLE
Heroku down [as of 2019-02-09]

### ISSUE THREAD

**Issue by pawroman** [vintasoftware/python-api-checklist#22]
Hi,

Just noticed that the website is down: https://devchecklists.com/python-api-checklist/

It returns HTTP 503 with the following:

```
Application error

An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail 
```

**Comment by fjsj** [comment]
Thanks for the report @pawroman
We'll investigate.

Could you please check this @felipefarias ?

**Comment by fjsj** [comment]
@pawroman it should be fine again now. Thanks again for reporting!
