### ISSUE TITLE
[Translation] translation for korean

### ISSUE THREAD

**Issue by mingrammer** [vintasoftware/python-api-checklist#9]
I've translated this repo to korean on my repository with github pages. and I commented for this on [reddit](https://www.reddit.com/r/Python/comments/6jtits/a_useful_checklist_for_build_good_python/djl8sls/)

This is URL of korean repository : https://github.com/mingrammer/python-api-checklist
This is github pages : https://mingrammer.com/python-api-checklist

So, you could add a link or a button on your original page for korean users :D

**Comment by fjsj** [comment]
Thanks @mingrammer ! I'll figure out the best way to integrate this and let you know.

**Comment by TheMushrr00m** [comment]
@fjsj maybe you could add a submenu to select language. I'm working on translating to spanish, and maybe i can modify the index to have a proposal into my repo.

**Comment by fjsj** [comment]
@TheMushrr00m A submenu is good. I would like to have all languages in the same domain (thus, same repo), with due authorship credits on each one. It would be great if you can do it in a fork and make a PR.

**Comment by filipeximenes** [comment]
You can just copy the structure from http://celerytaskschecklist.com/
It has support for multiple languages

**Comment by fjsj** [comment]
@mingrammer the language selection has been integrated by @TheMushrr00m !
@mingrammer, can you make a PR with the korean `checklist.md` file and the korean link in `index.html`?

**Comment by TheMushrr00m** [comment]
@mingrammer If you need something, let me know.

**Comment by mingrammer** [comment]
Ok, Thank you @TheMushrr00m ! So, I'll send you a PR on this evening (in korean time ) :D

**Comment by mingrammer** [comment]
I have a question. If someone click a some language, the title and simple description (~ checkbox blah blah ~) will be also changed?

**Comment by fjsj** [comment]
Good question @mingrammer
The code for the language was based on https://github.com/vintasoftware/celery-tasks-checklist/
As of today, it doesn't change the title and description. If you want, you can change that. Otherwise do without this and I'll create a issue to tackle this later. Thanks!

**Comment by mingrammer** [comment]
@fjsj First, I just added korean checklist, but not worked for changing the title and description now.

**Comment by TheMushrr00m** [comment]
@fjsj  I did make a PR to try to fix it!
Please check it and if it is correct, i can merge the the korean checklist from @mingrammer

**Comment by fjsj** [comment]
Closed by #14
